### ISSUE TITLE
Provide org submitting instructions after generation

### ISSUE THREAD

**Issue by lkubb** [salt-extensions/salt-extension-copier#15]
After generating a project that uses the `salt-extensions` namespace, there should be some instructions on how to submit an extension to the organization. I think it would be best if the working group came up with official instructions.

We could add them here:

https://github.com/salt-extensions/salt-extension-copier/blob/bc04e7682f247985c4a5dd1fa4af8cb24c8fcb66/copier.yml#L303-L346

Preliminary instructions are found in the new guide, we could just add the corresponding link after generation: https://salt-extensions.github.io/salt-extension-copier/topics/organization/submitting.html

This was originally reported here: https://github.com/salt-extensions/salt-extension-copier/issues/14

**Comment by dmurphy18** [comment]
Would also be good to include instructions on submitting the new extension to PyPI too

**Comment by lkubb** [comment]
Yup. In the end, the process depends on whether one is in the org and uses the centralized workflows (a release is just a tag away) or has a different setup (there's currently no scaffolding for releases).

I think it might be time for a more general documentation regarding the process instead of bloating the post-generation message, see https://github.com/salt-extensions/salt-extension-copier/issues/17

Also opened a separate issue about improving the release tooling: https://github.com/salt-extensions/salt-extension-copier/issues/18
